services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    restart: unless-stopped
    networks:
      - app-net

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: unless-stopped
    networks:
      - app-net
    dns:
      - 8.8.8.8
      - 8.8.4.4

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - client
      - server
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
