FROM node:20-alpine
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app
COPY pnpm-lock.yaml pnpm-workspace.yaml ./
COPY client/package.json ./client/
COPY server/package.json ./server/
COPY shared ./shared/

# Install dependencies globally in the container.
# This avoids breaking PNPM symlinks which happens when copying node_modules across multistage builds!
RUN pnpm install --frozen-lockfile

COPY server ./server/
RUN pnpm --filter server build

WORKDIR /app/server
EXPOSE 3001
CMD ["npm", "run", "start"]
